### ISSUE TITLE
Please provide instruction to get the vcenter admin password

### ISSUE THREAD

**Issue by romainsc** [RedHatDemos/RHS-Migration_Analytics#21]
Hi,

in the lab documentation, the “doc/migration_analytics-lab_guide.adoc” states “Use the administrator username which is administrator@vsphere.local and the provided password.” 
but no password is provided in the RHPDS email or catalog page or any other internal documentation and no instruction is provided in order to find it with other internal resources.

For RHTE, I presume it have been displayed on the presentation.

Best Regards,

**Comment by romainsc** [comment]
Same for:

- CFME admin password
- root password of cfme vm

**Comment by bthurber** [comment]
Submitted PR:  https://github.com/RedHatDemos/RHS-Migration_Analytics/pull/22

**Comment by mmmmmmpc** [comment]
Merged PR
Closing issue
Thanks!
